lessons:
  outputs:
    dev:
      account: niraphr-vlb67401
      database: EXERCISE_DB
      password: OanaNicolae20
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 64
      type: snowflake
      user: OANANICOLAE
      warehouse: COMPUTE_WH
  target: dev